### ISSUE TITLE
Graceful shutdown of run does not work perfectly

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#348]
## 🙂 Expected behavior

When I stop sunodo node using CTRL-C that I executed with `sunodo run` it should terminate gracefully, stop all containers and remove them.

## 🫠 Actual behavior

What is happening instead?
The containers are stopped and removed, but it is printing the alarming message below:

```
panic: close of closed channel

goroutine 528 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).Up.func2.1.1()
        github.com/docker/compose/v2/pkg/compose/up.go:81 +0xa4
github.com/hashicorp/go-multierror.(*Group).Go.func1()
        github.com/hashicorp/go-multierror@v1.1.1/group.go:23 +0x60
created by github.com/hashicorp/go-multierror.(*Group).Go in goroutine 293
        github.com/hashicorp/go-multierror@v1.1.1/group.go:20 +0x84
```

It looks like docker compose is raising an exception, which causes the execution to exit with an error code 2.

```
    Error: Command failed with exit code 2: docker compose --file /opt/homebrew/Cellar/sunodo/0.10.3/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-validator.yaml --file 
    /opt/homebrew/Cellar/sunodo/0.10.3/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-database.yaml --file 
    /opt/homebrew/Cellar/sunodo/0.10.3/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-proxy.yaml --file 
    /opt/homebrew/Cellar/sunodo/0.10.3/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-anvil.yaml --file 
    /opt/homebrew/Cellar/sunodo/0.10.3/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-explorer.yaml --file 
    /opt/homebrew/Cellar/sunodo/0.10.3/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-snapshot-volume.yaml --project-directory . --project-name af28c486 up --attach 
    validator --attach prompt
```

## 🧪 Minimal test case

```shell
sunodo run
# CTRL-C to stop it
```

## 🌎 Environment

macOS Sonoma 14.2.1 (M1)
Docker Desktop 4.26.1 (131620) is currently the newest version available.
Docker Compose version v2.23.3-desktop.2
sunodo 0.10.3

## ✔️ Possible solutions

I trying replacing the 2.23 version of docker compose plugin by the version release yesterday 2.24, thinking that the problem could be similar to this [closed issue](https://github.com/docker/compose/issues/11280), but it did not work as well.

**Comment by endersonmaia** [comment]
Just for the record, this issues doesn't happen on my environment:

```
❯ docker compose version
Docker Compose version v2.23.3
❯ docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:58 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:58 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by endersonmaia** [comment]
I could reproduce the error on an `linux/arm64` environment, maybe it's related to `golang/arm64` and we should upstream this bug report.

```shell
[ec2-user@ip-10-0-63-164 my-ts-dapp]$ docker compose version
Docker Compose version v2.24.0
[ec2-user@ip-10-0-63-164 my-ts-dapp]$ docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        ced0996
 Built:             Tue Nov 14 00:00:00 2023
 OS/Arch:           linux/arm64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       a61e2b4
  Built:            Tue Nov 14 00:00:00 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:          1.1.7
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
